blank_issues_enabled: false
contact_links:
  - name: Eterna Forum
    url: https://forum.eternagame.org
    about: If you are an Eterna player, please use the forum to submit feedback.
  - name: Eterna Discord
    url: https://discord.gg/KYeTwux
    about: For questions and other discussion, please join us on the Eterna Discord server.